Add tpm2 support to vaultboot
Changelog-public-20210907:

* Use runtime-determined boot device path in our targets
* Make boot device able to be denoted by label
* Test grsec support against linux-5.4.68
* Update all our target to use linux-5.4.68
* Introduce a common config for linux kernel
* Make the path to crypttab within initramfs overridable
* Add an option allowing automatically unlocking LUKS

Signed-off-by: HardenedVault <root@hardenedvault.net>

diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -42,13 +42,15 @@ read -s -p "Enter disk recovery key: " disk_password
 echo -n "$disk_password" > "$RECOVERY_KEY"
 echo
 
-read -s -p "New disk unlock password for booting: " key_password
-echo
-read -s -p "Repeat unlock code: " key_password2
-echo
+if [ "$CONFIG_AUTO_UNLOCK" != y ]; then
+	read -s -p "New disk unlock password for booting: " key_password
+	echo
+	read -s -p "Repeat unlock code: " key_password2
+	echo
 
-if [ "$key_password" != "$key_password2" ]; then
-	die "Key passwords do not match"
+	if [ "$key_password" != "$key_password2" ]; then
+		die "Key passwords do not match"
+	fi
 fi
 
 # Generate key file
@@ -82,72 +84,121 @@ done
 # since it should still be zero
 cat "$KEY_DEVICES" | cut -d\  -f1 | xargs /bin/qubes-measure-luks \
 	|| die "Unable to measure the LUKS headers"
-luks_pcr=`tpm calcfuturepcr -ix 16 -if /tmp/luksDump.txt`
 
-# HOTP USB Secrity Dongle loads USB modules which changes PCR5.
-# In the event HOTP USB Security Dongle is enabled, skip verification of PCR5
-if [ -x /bin/hotp_verification ]; then
-  pcr_5="X"
-else
-  pcr_5="0000000000000000000000000000000000000000"
-fi
+if [ "$CONFIG_TPM" = "y" ];then
+	luks_pcr=`tpm calcfuturepcr -ix 16 -if /tmp/luksDump.txt`
+	# HOTP USB Secrity Dongle loads USB modules which changes PCR5.
+	# In the event HOTP USB Security Dongle is enabled, skip verification of PCR5
+	# If modules should be loaded during normal boot, skip verification of PCR5
+	if [ "$CONFIG_USB_KEYBOARD" = "y" -o -r /lib/modules/libata.ko -o -x /bin/hotp_verification ]; then
+		pcr_5="X"
+	else
+		pcr_5="0000000000000000000000000000000000000000"
+	fi
 
-# Note that PCR 4 needs to be set with the "normal-boot"
-# path value, which we do not have right now since we are
-# in a recovery shell.
-# used to be -ix 4 f8fa3b6e32e7c6fe04c366e74636e505b28f3b0d \
-# now just all zeros in a normal boot
-# PCR 5 must be all zero since no kernel modules should have
-# been loaded during a normal boot, but might have been
-# loaded in the recovery shell.
-# Otherwise use the current values of the PCRs, which will be read
-# from the TPM as part of the sealing ("X").
-tpm sealfile2 \
-	-if "$KEY_FILE" \
-	-of "$TPM_SEALED" \
-	-pwdd "$key_password" \
-	-hk 40000000 \
-	-ix 0 X \
-	-ix 1 X \
-	-ix 2 X \
-	-ix 3 X \
-	-ix 4 0000000000000000000000000000000000000000 \
-	-ix 5 $pcr_5 \
-	-ix 6 $luks_pcr \
-	-ix 7 X \
-|| die "Unable to seal secret"
+	# Note that PCR 4 needs to be set with the "normal-boot"
+	# path value, which we do not have right now since we are
+	# in a recovery shell.
+	# used to be -ix 4 f8fa3b6e32e7c6fe04c366e74636e505b28f3b0d \
+		# now just all zeros in a normal boot
+	# PCR 5 must be all zero since no kernel modules should have
+	# been loaded during a normal boot, but might have been
+	# loaded in the recovery shell.
+	# Otherwise use the current values of the PCRs, which will be read
+	# from the TPM as part of the sealing ("X").
+	if [ "$CONFIG_AUTO_UNLOCK" != y ]; then
+		tpm sealfile2 \
+		    -if "$KEY_FILE" \
+		    -of "$TPM_SEALED" \
+		    -pwdd "$key_password" \
+		    -hk 40000000 \
+		    -ix 0 X \
+		    -ix 1 X \
+		    -ix 2 X \
+		    -ix 3 X \
+		    -ix 4 0000000000000000000000000000000000000000 \
+		    -ix 5 $pcr_5 \
+		    -ix 6 $luks_pcr \
+		    -ix 7 X
+	else
+		tpm sealfile2 \
+		    -if "$KEY_FILE" \
+		    -of "$TPM_SEALED" \
+		    -hk 40000000 \
+		    -ix 0 X \
+		    -ix 1 X \
+		    -ix 2 X \
+		    -ix 3 X \
+		    -ix 4 0000000000000000000000000000000000000000 \
+		    -ix 5 $pcr_5 \
+		    -ix 6 $luks_pcr \
+		    -ix 7 X
+	fi
 
-shred -n 10 -z -u "$KEY_FILE" 2> /dev/null \
-|| die "Failed to delete key file"
+	if [ $? -ne 0 ]; then
+		die "Unable to seal secret"
+	fi
 
-# try it without the owner password first
-if ! tpm nv_writevalue \
-	-in $TPM_INDEX \
-	-if "$TPM_SEALED" \
-; then
-	# to create an nvram space we need the TPM owner password
-	# and the TPM physical presence must be asserted.
-	#
-	# The permissions are 0 since there is nothing special
-	# about the sealed file
-	tpm physicalpresence -s \
-	|| warn "Warning: Unable to assert physical presence"
+	shred -n 10 -z -u "$KEY_FILE" 2> /dev/null \
+		|| die "Failed to delete key file"
 
-	read -s -p "TPM Owner password: " tpm_password
-	echo
+	# try it without the owner password first
+	if ! tpm nv_writevalue \
+	     -in $TPM_INDEX \
+	     -if "$TPM_SEALED" \
+	   ; then
+		# to create an nvram space we need the TPM owner password
+		# and the TPM physical presence must be asserted.
+		#
+		# The permissions are 0 since there is nothing special
+		# about the sealed file
+		tpm physicalpresence -s \
+			|| warn "Warning: Unable to assert physical presence"
 
-	tpm nv_definespace \
-		-in $TPM_INDEX \
-		-sz $TPM_SIZE \
-		-pwdo "$tpm_password" \
-		-per 0 \
-	|| warn "Warning: Unable to define NVRAM space; trying anyway"
+		read -s -p "TPM Owner password: " tpm_password
+		echo
+
+		tpm nv_definespace \
+		    -in $TPM_INDEX \
+		    -sz $TPM_SIZE \
+		    -pwdo "$tpm_password" \
+		    -per 0 \
+			|| warn "Warning: Unable to define NVRAM space; trying anyway"
 
 
-	tpm nv_writevalue \
-		-in $TPM_INDEX \
-		-if "$TPM_SEALED" \
-	|| die "Unable to write sealed secret to NVRAM"
+		tpm nv_writevalue \
+		    -in $TPM_INDEX \
+		    -if "$TPM_SEALED" \
+			|| die "Unable to write sealed secret to NVRAM"
+	fi
+elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	pcrf="/tmp/secret/pcrf.bin"
+	tpm2 pcrread -o "$pcrf" sha256:0,1,2,3
+	# pcr 4 is expected to be zero
+	dd if=/dev/zero bs=32 count=1 >> "$pcrf"
+	if [ "$CONFIG_USB_KEYBOARD" = "y" -o -r /lib/modules/libata.ko -o -x /bin/hotp_verification ]; then
+		# binary pcr dump can only go via stderr for redirection
+		# sadly this busybox has buggy support for "2>>" and "2|"
+		# so we need workaround...
+		tpm2 pcrread -o /dev/stderr sha256:5 2>&1 >/dev/console | cat >> "$pcrf"
+	else
+		dd if=/dev/zero bs=32 count=1 >> "$pcrf"
+	fi
+	# Use pcr 23 to precompute the value for pcr 6
+	tpmr extend -ix 23 -if /tmp/luksDump.txt
+	tpm2 pcrread -o /dev/stderr sha256:23 2>&1 >/dev/console | cat >> "$pcrf"
+	tpm2 pcrreset 23
+	tpm2 pcrread -o /dev/stderr sha256:7 2>&1 >/dev/console | cat >> "$pcrf"
+	if [ "$CONFIG_AUTO_UNLOCK" = "y" ]; then
+		tpmr seal "$KEY_FILE" "0x8100000$TPM_INDEX" sha256:0,1,2,3,4,5,6,7 "$pcrf"
+	else
+		tpmr seal "$KEY_FILE" "0x8100000$TPM_INDEX" sha256:0,1,2,3,4,5,6,7 "$pcrf" "$key_password"
+	fi
+	if [ $? -eq 0 ]; then
+		# should be okay if this fails
+		shred -n 10 -z -u "$pcrf".* 2> /dev/null || true
+		exit 0
+	fi
 fi
 
 shred -n 10 -z -u "$TPM_SEALED" 2> /dev/null \
diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -297,23 +297,24 @@ do_boot()
 		die "!!! Missing required boot hashes"
 	fi
 
-	if [ "$CONFIG_TPM" = "y" \
-		-a -r "$TMP_KEY_DEVICES" ]; then
-		INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
-		|| die "!!! Failed to extract the initrd from boot option"
-		if [ -z "$INITRD" ]; then
-			die "!!! No initrd file found in boot option"
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		if [ -r "$TMP_KEY_DEVICES" ]; then
+			INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
+				|| die "!!! Failed to extract the initrd from boot option"
+			if [ -z "$INITRD" ]; then
+				die "!!! No initrd file found in boot option"
+			fi
+
+			kexec-insert-key $INITRD \
+				|| die "!!! Failed to insert disk key into a new initrd"
+
+			kexec-boot -b "$bootdir" -e "$option" \
+				   -a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
+				|| die "!!! Failed to boot w/ options: $option"
+		else
+			kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
+				|| die "!!! Failed to boot w/ options: $option"
 		fi
-
-		kexec-insert-key $INITRD \
-		|| die "!!! Failed to insert disk key into a new initrd"
-
-		kexec-boot -b "$bootdir" -e "$option" \
-			-a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
-		|| die "!!! Failed to boot w/ options: $option"
-	else
-		kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
-		|| die "!!! Failed to boot w/ options: $option"
 	fi
 }
 
@@ -341,11 +342,12 @@ while true; do
 		user_select
 	fi
 
-	if [ "$CONFIG_TPM" = "y" \
-		-a ! -r "$TMP_KEY_DEVICES" ]; then
-		# Extend PCR4 as soon as possible
-		tpm extend -ix 4 -ic generic \
-		|| die "Failed to extend PCR 4"
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		if [ ! -r "$TMP_KEY_DEVICES" ]; then
+			# Extend PCR4 as soon as possible
+			tpmr extend -ix 4 -ic generic \
+				|| die "Failed to extend PCR 4"
+		fi
 	fi
 
 	# if no saved options, scan the boot directory and generate
@@ -353,7 +355,7 @@ while true; do
 		scan_options
 	fi
 
-	if [ "$CONFIG_TPM" = "y" ]; then
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
 		# Optionally enforce device file hashes
 		if [ -r "$TMP_HASH_FILE" ]; then
 			valid_global_hash="n"
@@ -365,7 +367,7 @@ while true; do
 			fi
 		fi
 
-		if [ -r "$TMP_ROLLBACK_FILE" ]; then
+		if [ "$CONFIG_IGNORE_ROLLBACK" != "y" -a -r "$TMP_ROLLBACK_FILE" ]; then
 			# in the case of iso boot with a rollback file, do not assume valid
 			valid_rollback="n"
 
diff --git a/initrd/bin/kexec-unseal-key b/initrd/bin/kexec-unseal-key
--- a/initrd/bin/kexec-unseal-key
+++ b/initrd/bin/kexec-unseal-key
@@ -16,27 +16,51 @@ key_file="$1"
 if [ -z "$key_file" ]; then
 	key_file="/tmp/secret/secret.key"
 fi
+if [ "$CONFIG_TPM" = "y" ];then
+	tpm nv_readvalue \
+	    -in "$TPM_INDEX" \
+	    -sz "$TPM_SIZE" \
+	    -of "$sealed_file" \
+		|| die "Unable to read key from TPM NVRAM"
 
-tpm nv_readvalue \
-	-in "$TPM_INDEX" \
-	-sz "$TPM_SIZE" \
-	-of "$sealed_file" \
-|| die "Unable to read key from TPM NVRAM"
+	for tries in 1 2 3; do
+		if [ "$CONFIG_AUTO_UNLOCK" != y ]; then
+			read -s -p "Enter unlock password (blank to abort): " tpm_password
+			echo
+			if [ -z "$tpm_password" ]; then
+				die "Aborting unseal disk encryption key"
+			fi
 
-for tries in 1 2 3; do
-	read -s -p "Enter unlock password (blank to abort): " tpm_password
-	echo
+			tpm unsealfile \
+			    -if "$sealed_file" \
+			    -of "$key_file" \
+			    -pwdd "$tpm_password" \
+			    -hk 40000000
+		else
+			tpm unsealfile \
+			    -if "$sealed_file" \
+			    -of "$key_file" \
+			    -hk 40000000
+		fi
 
-	if [ -z "$tpm_password" ]; then
-		die "Aborting unseal disk encryption key"
+		if [ $? -eq 0 ]; then
+			# should be okay if this fails
+			shred -n 10 -z -u /tmp/secret/sealed 2> /dev/null || true
+			exit 0
+		fi
+
+		pcrs
+		warn "Unable to unseal disk encryption key"
+	done
+elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	for tries in 1 2 3; do
+	if [ "$CONFIG_AUTO_UNLOCK" = "y" ]; then
+		tpmr unseal "0x8100000$TPM_INDEX" "sha256:0,1,2,3,4,5,6,7" > "$key_file"
+	else
+		tpmr unseal "0x8100000$TPM_INDEX" "sha256:0,1,2,3,4,5,6,7" "file:-" > "$key_file"
 	fi
 
-	if tpm unsealfile \
-		-if "$sealed_file" \
-		-of "$key_file" \
-		-pwdd "$tpm_password" \
-		-hk 40000000 \
-	; then
+	if [ $? -eq 0 ]; then
 		# should be okay if this fails
 		shred -n 10 -z -u /tmp/secret/sealed 2> /dev/null || true
 		exit 0
@@ -45,5 +69,6 @@ for tries in 1 2 3; do
 	pcrs
 	warn "Unable to unseal disk encryption key"
 done
+fi
 
 die "Retry count exceeded..."
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -22,8 +22,8 @@ recovery() {
 	# ensure /tmp/config exists for recovery scripts that depend on it
 	touch /tmp/config
 
-	if [ "$CONFIG_TPM" = y ]; then
-		tpm extend -ix 4 -ic recovery
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		tpmr extend -ix 4 -ic recovery
 	fi
 
 	while [ true ]
@@ -47,7 +47,11 @@ pause_recovery() {
 }
 
 pcrs() {
-	head -8 /sys/class/tpm/tpm0/pcrs
+	if [ "$CONFIG_TPM" = "y" ]; then
+		head -8 /sys/class/tpm/tpm0/pcrs
+	elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		tpm2 pcrread sha256
+	fi
 }
 
 confirm_totp()
@@ -62,7 +66,7 @@ confirm_totp()
 		date=`date "+%Y-%m-%d %H:%M:%S"`
 		seconds=`date "+%s"`
 		half=`expr \( $seconds % 60 \) / 30`
-		if [ "$CONFIG_TPM" != y ]; then
+		if [ "$CONFIG_TPM" != "y" -a "$CONFIG_TPM2_TOOLS" != "y" ]; then
 			TOTP="NO TPM"
 		elif [ "$half" != "$last_half" ]; then
 			last_half=$half;
@@ -132,6 +136,34 @@ enable_usb()
 
 }
 
+enable_sata()
+{
+	for mod in libata libahci ahci; do
+		if ! lsmod | grep -q "^$mod " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ ! -z "$1" ]; then
+		exec mount "$@"
+	fi
+}
+
+enable_nvme()
+{
+	for mod in nvme-core nvme; do
+		if ! lsmod | grep -q "^$mod " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ ! -z "$1" ]; then
+		exec mount "$@"
+	fi
+}
+
 confirm_gpg_card()
 {
 	read \
@@ -186,7 +218,7 @@ check_tpm_counter()
 		warn "$1 does not exist; creating new TPM counter"
 		read -s -p "TPM Owner password: " tpm_password
 		echo
-		tpm counter_create \
+		tpmr counter_create \
 			-pwdo "$tpm_password" \
 			-pwdc '' \
 			-la $LABEL \
@@ -202,13 +234,13 @@ check_tpm_counter()
 
 read_tpm_counter()
 {
-	tpm counter_read -ix "$1" | tee "/tmp/counter-$1" \
+	tpmr counter_read -ix "$1" | tee "/tmp/counter-$1" \
 	|| die "Counter read failed"
 }
 
 increment_tpm_counter()
 {
-	tpm counter_increment -ix "$1" -pwdc '' \
+	tpmr counter_increment -ix "$1" -pwdc '' \
 		| tee /tmp/counter-$1 \
 	|| die "Counter increment failed"
 }
@@ -290,8 +322,10 @@ update_checksums()
 
 	# sign and auto-roll config counter
 	extparam=
-	if [ "$CONFIG_TPM" = "y" ]; then
-		extparam=-r
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ];then
+		if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
+			extparam=-r
+		fi
 	fi
 	if ! kexec-sign-config -p /boot -u $extparam ; then
 		rv=1
@@ -303,6 +337,20 @@ update_checksums()
 	mount -o ro,remount /boot
 
 	return $rv
+}
+
+# evaluate key-value pair like 'LABEL=boot' to real path
+# busybox's blkid only supports LABEL and UUID
+evaluate_boot_device()
+{
+	if echo "$1" | grep -q '^/'; then
+		# if $1 contains an absolute path, output it as-is
+		echo "$1"
+	else
+		key="$(echo $1 | cut -f1 -d =)"
+		value="$(echo $1 | cut -f2 -d =)"
+		blkid | grep "$key=\"$value\"" | cut -f1 -d ':'
+	fi
 }
 
 # detect and set /boot device
@@ -379,4 +427,14 @@ generate_random_mac_address()
 {
 	#Borrowed from https://stackoverflow.com/questions/42660218/bash-generate-random-mac-address-unicast
 	hexdump -n 6 -ve '1/1 "%.2x "' /dev/urandom | awk -v a="2,6,a,e" -v r="$RANDOM" 'BEGIN{srand(r);}NR==1{split(a,b,",");r=int(rand()*4+1);printf "%s%s:%s:%s:%s:%s:%s\n",substr($1,0,1),b[r],$2,$3,$4,$5,$6}'
+}
+
+lock_chip() {
+	APM_CNT=0xb2
+	COMMON_LOCK=0xcb
+	VAULT_LOCK=0xfa
+	echo "VaultFW locking"
+	io386 -o b -b x $APM_CNT $VAULT_LOCK
+	echo "Common locking"
+	io386 -o b -b x $APM_CNT $COMMON_LOCK
 }
