Add remote attestation support to vaultboot
Changelog-public-20220627:

* Add experimental support for Raspberry 4
* Allow to build kernel and initrd without building firmware image
* Allow musl-cross to be built manually
* Allow parallelized building
* Add basic MMC/SD card support
* Add TPM2 primary key to the hash tree
* Set system time to BUILD_TIME on boards without an RTC
* Use cryptsetup2 by default
* Use cryptsetup-2.4.3 for cryptsetup2
* Use luksHeaderBackup rather than luksDump to measure luks headers
* Add a more precise notification for the input of encrypt devices
* Make it possible to report headers of which LUKSes to be unlocked via TPM change
* Add remote attestation support
* Upgrade tpm2-tss and tpm2-tools
* Add a random passphrase to platform hierarchy of TPM2 before kexec
* Enable X2APIC support on Linux kernel
* Update Linux kernel to 5.15.45
* Add 'halt' to shutdown the computer gracefully

Signed-off-by: HardenedVault <root@hardenedvault.net>

diff --git a/initrd/bin/kexec-insert-key b/initrd/bin/kexec-insert-key
--- a/initrd/bin/kexec-insert-key
+++ b/initrd/bin/kexec-insert-key
@@ -55,6 +55,21 @@ unseal_failed="n"
 if ! kexec-unseal-key "$INITRD_DIR/secret.key" ; then
 	unseal_failed="y"
 	echo "!!! Failed to unseal the TPM LUKS disk key"
+elif [ "$CONFIG_ATTEST_TOOLS" = "y" ]; then
+	if [ -r $bootdir/kexec_attest_server.txt ]; then
+		attest_server=$(cat $bootdir/kexec_attest_server.txt)
+	fi
+	export attest_server
+	if ! kexec-attest "$INITRD_DIR/attest.key"; then
+		unseal_failed="y"
+		echo "!!! Failed to obtain remote attestation key"
+	else
+		tpmr extend -ix 11 -ic generic \
+			|| die 'Unable to scramble PCR 11'
+		# Append attest key after the local key
+		cat "$INITRD_DIR/attest.key" >> "$INITRD_DIR/secret.key"
+		shred -n 10 -z -u "$INITRD_DIR/attest.key" 2> /dev/null || true
+	fi
 fi
 
 # Override PCR 4 so that user can't read the key
@@ -63,6 +78,8 @@ tpmr extend -ix 4 -ic generic \
 
 # Check to continue
 if [ "$unseal_failed" = "y" ]; then
+	diff "$(dirname $INITRD)/kexec_lukshdr_hash.txt" /tmp/luksDump.txt \
+		&& echo "Headers of LUKSes to be unlocked via TPM do not change."
 	confirm_boot="n"
 	read \
 		-n 1 \
diff --git a/initrd/bin/kexec-seal-key b/initrd/bin/kexec-seal-key
--- a/initrd/bin/kexec-seal-key
+++ b/initrd/bin/kexec-seal-key
@@ -62,6 +62,24 @@ dd \
 	2>/dev/null \
 || die "Unable to generate 128 random bytes"
 
+if [ "$CONFIG_TPM2_TOOLS" = "y" -a "$CONFIG_ATTEST_TOOLS" = "y" ]; then
+	echo "Bring up network for remote attestation"
+	network-init-recovery
+	if [ -r $paramsdir/kexec_attest_server.txt ]; then
+		attest_server=$(cat $paramsdir/kexec_attest_server.txt)
+	fi
+	export attest_server
+	if ! kexec-attest "$KEY_FILE.attest"; then
+		die "Failed to obtain remote attestation key"
+	else
+		# Append attest key after the local key
+		cat "$KEY_FILE" "$KEY_FILE.attest" > "$KEY_FILE.real"
+		shred -n 10 -z -u "$KEY_FILE.attest" 2> /dev/null || true
+	fi
+else
+	cp "$KEY_FILE" "$KEY_FILE.real"
+fi
+
 # Remove all the old keys from slot 1
 for dev in `cat "$KEY_DEVICES" | cut -d\  -f1`; do
 	echo "++++++ $dev: Removing old key slot"
@@ -74,9 +92,11 @@ for dev in `cat "$KEY_DEVICES" | cut -d\  -f1`; do
 	cryptsetup luksAddKey \
 		--key-file "$RECOVERY_KEY" \
 		--key-slot 1 \
-		$dev "$KEY_FILE" \
+		$dev "$KEY_FILE.real" \
 	|| die "$dev: Unable to add key"
 done
+shred -n 10 -z -u "$KEY_FILE.real" 2> /dev/null \
+|| warn "Failed to erase the real FDE key - continuing"
 
 # Now that we have setup the new keys, measure the PCRs
 # We don't care what ends up in PCR 6; we just want
@@ -197,9 +217,11 @@ elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
 	if [ $? -eq 0 ]; then
 		# should be okay if this fails
 		shred -n 10 -z -u "$pcrf".* 2> /dev/null || true
-		exit 0
 	fi
 fi
 
 shred -n 10 -z -u "$TPM_SEALED" 2> /dev/null \
 || warn "Failed to delete the sealed secret - continuing"
+
+cp /tmp/luksDump.txt "$paramsdir/kexec_lukshdr_hash.txt" \
+|| warn "Failed to have hashes of LUKS header - continuing"
diff --git a/initrd/bin/kexec-select-boot b/initrd/bin/kexec-select-boot
--- a/initrd/bin/kexec-select-boot
+++ b/initrd/bin/kexec-select-boot
@@ -48,6 +48,22 @@ bootdir="${bootdir%%/}"
 paramsdev="${paramsdev%%/}"
 paramsdir="${paramsdir%%/}"
 
+PRIMHASH_FILE="$paramsdir/kexec_primhdl_hash.txt"
+if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	if [ -r "$PRIMHASH_FILE" ]; then
+		sha256sum -c "$PRIMHASH_FILE" \
+			|| {
+			echo "FATAL: Hash of TPM2 primary key handle mismatch!";
+			echo "If you have not intentionally regenerated TPM2 primary key,";
+			die "your system may have been compromised!";
+		}
+	else
+		echo "WARNING: Hash of TPM2 primary key handle does not exist!"
+		echo "Please rebuild the boot hash tree."
+		default_failed="y"
+	fi
+fi
+
 verify_global_hashes()
 {
 	echo "+++ Checking verified boot hash file "
@@ -297,24 +313,22 @@ do_boot()
 		die "!!! Missing required boot hashes"
 	fi
 
-	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
-		if [ -r "$TMP_KEY_DEVICES" ]; then
-			INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
-				|| die "!!! Failed to extract the initrd from boot option"
-			if [ -z "$INITRD" ]; then
-				die "!!! No initrd file found in boot option"
-			fi
-
-			kexec-insert-key $INITRD \
-				|| die "!!! Failed to insert disk key into a new initrd"
-
-			kexec-boot -b "$bootdir" -e "$option" \
-				   -a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
-				|| die "!!! Failed to boot w/ options: $option"
-		else
-			kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
-				|| die "!!! Failed to boot w/ options: $option"
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] && [ -r "$TMP_KEY_DEVICES" ]; then
+		INITRD=`kexec-boot -b "$bootdir" -e "$option" -i` \
+			|| die "!!! Failed to extract the initrd from boot option"
+		if [ -z "$INITRD" ]; then
+			die "!!! No initrd file found in boot option"
 		fi
+
+		kexec-insert-key $INITRD \
+			|| die "!!! Failed to insert disk key into a new initrd"
+
+		kexec-boot -b "$bootdir" -e "$option" \
+			   -a "$add" -r "$remove" -o "/tmp/secret/initrd.cpio" \
+			|| die "!!! Failed to boot w/ options: $option"
+	else
+		kexec-boot -b "$bootdir" -e "$option" -a "$add" -r "$remove" \
+			|| die "!!! Failed to boot w/ options: $option"
 	fi
 }
 
diff --git a/initrd/bin/tpmr b/initrd/bin/tpmr
--- a/initrd/bin/tpmr
+++ b/initrd/bin/tpmr
@@ -5,6 +5,7 @@ SECRET_DIR="/tmp/secret"
 PRIMARY_HANDLE="0x81000000"
 ENC_SESSION_FILE="enc.ctx"
 DEC_SESSION_FILE="dec.ctx"
+PRIMARY_HANDLE_FILE="primary.handle"
 
 set -e -o pipefail
 if [ -r "/tmp/config" ]; then
@@ -99,8 +100,20 @@ tpm2_counter_cre() {
 
 tpm2_startsession() {
 	mkdir -p "$SECRET_DIR"
-	tpm2 startauthsession -c "$PRIMARY_HANDLE" --hmac-session -S "/tmp/$ENC_SESSION_FILE"
-	tpm2 startauthsession -c "$PRIMARY_HANDLE" --hmac-session -S "/tmp/$DEC_SESSION_FILE"
+	tpm2 flushcontext \
+		--transient-object \
+		|| die "tpm2_flushcontext: unable to flush transient handles"
+
+	tpm2 flushcontext \
+		--loaded-session \
+		|| die "tpm2_flushcontext: unable to flush sessions"
+
+	tpm2 flushcontext \
+		--saved-session \
+		|| die "tpm2_flushcontext: unable to flush saved session"
+	tpm2 readpublic -c "$PRIMARY_HANDLE" -t "/tmp/$PRIMARY_HANDLE_FILE"
+	tpm2 startauthsession -c "/tmp/$PRIMARY_HANDLE_FILE" --hmac-session -S "/tmp/$ENC_SESSION_FILE"
+	tpm2 startauthsession -c "/tmp/$PRIMARY_HANDLE_FILE" --hmac-session -S "/tmp/$DEC_SESSION_FILE"
 	tpm2 sessionconfig --disable-encrypt "/tmp/$DEC_SESSION_FILE"
 }
 
@@ -114,11 +127,11 @@ tpm2_sealfile() {
 	bname="`basename $file`"
 	tpm2 createpolicy --policy-pcr -l "$pcrl" -f "$pcrf" -L "$SECRET_DIR/pcr.policy"
 	if [ "$pass" ];then
-		tpm2 create -C "$PRIMARY_HANDLE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE" -p "$pass"
+		tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE" -p "$pass"
 	else
-		tpm2 create -C "$PRIMARY_HANDLE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE"
+		tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE"
 	fi
-	tpm2 load -C "$PRIMARY_HANDLE" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -c "$SECRET_DIR/$bname.seal.ctx"
+	tpm2 load -C "/tmp/$PRIMARY_HANDLE_FILE" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -c "$SECRET_DIR/$bname.seal.ctx"
 	read -s -p "New TPM owner password: " key_password
 	# remove possible data occupying this handle
 	tpm2 evictcontrol -C o -P "$key_password" -c "$handle" 2>/dev/null || true
@@ -156,10 +169,11 @@ tpm2_reset() {
 		die "Key passwords do not match"
 	fi
 	mkdir -p "$SECRET_DIR"
-	tpm2 clear -c platform
+	tpm2 clear -c platform || warn "Unable to clear TPM on platform hierarchy!"
 	tpm2 changeauth -c owner "$key_password"
 	tpm2 createprimary -C owner -g sha256 -G "${CONFIG_PRIMARY_KEY_TYPE:-rsa}" -c "$SECRET_DIR/primary.ctx" -P "$key_password"
 	tpm2 evictcontrol -C owner -c "$SECRET_DIR/primary.ctx" "$PRIMARY_HANDLE" -P "$key_password"
+	shred -u "$SECRET_DIR/primary.ctx"
 	tpm2_startsession
 }
 subcmd="$1"
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -93,6 +93,22 @@ confirm_totp()
 	echo
 }
 
+enable_mmc_core()
+{
+	for mod in mmc_core mmc_block; do
+		if ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+	# mfd-core may be linked into kernel on some architecture
+	mod="mfd-core"
+	if [ -r "/lib/modules/$mod.ko" ] && ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+		insmod "/lib/modules/$mod.ko" \
+			|| die "$mod: Unable to load module"
+	fi
+}
+
 enable_usb()
 {
 	if [ "$CONFIG_LINUX_USB_COMPANION_CONTROLLER" = y ]; then
@@ -134,12 +150,21 @@ enable_usb()
 		fi
 	fi
 
+	if [ -r "/lib/modules/mmc_core.ko" ]; then
+		enable_mmc_core
+		for mod in rtsx_usb rtsx_usb_sdmmc vub300; do
+			if [ -r "/lib/modules/$mod.ko" ] && ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+				insmod "/lib/modules/$mod.ko" \
+					|| die "$mod: Unable to load module"
+			fi
+		done
+	fi
 }
 
 enable_sata()
 {
 	for mod in libata libahci ahci; do
-		if ! lsmod | grep -q "^$mod " ; then
+		if ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
 			insmod "/lib/modules/$mod.ko" \
 				|| die "$mod: Unable to load module"
 		fi
@@ -153,7 +178,43 @@ enable_sata()
 enable_nvme()
 {
 	for mod in nvme-core nvme; do
-		if ! lsmod | grep -q "^$mod " ; then
+		if ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ ! -z "$1" ]; then
+		exec mount "$@"
+	fi
+}
+
+enable_mmc()
+{
+	enable_mmc_core
+	for mod in sdhci cqhci sdhci-acpi sdhci-pci rtsx_pci rtsx_pci_sdmmc; do
+		if ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ -r /lib/modules/sdhci-pltfm.ko ]; then
+		for mod in sdhci-pltfm bcm2835 dw_mmc dw_mmc-pltfm dw_mmc-k3 \
+				       dw_mmc-rockchip meson-gx-mmc crc7 crc-itu-t \
+				       of_mmc_spi mmc_spi sdhci-esdhc-imx sdhci_f_sdh30 \
+				       sdhci-iproc sdhci-msm sdhci-of-arasan sdhci-of-esdhc \
+				       sdhci-tegra sdhci-xenon-driver sunxi-mmc; do
+			if ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+				insmod "/lib/modules/$mod.ko" \
+					|| die "$mod: Unable to load module"
+			fi
+		done
+	fi
+
+	# minor drivers, only loaded while existing
+	for mod in cb710 cb710-mmc tifm_core tifm_sd toshsd via-sdmmc bcm2835-mmc; do
+		if [ -r "/lib/modules/$mod.ko" ] && ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
 			insmod "/lib/modules/$mod.ko" \
 				|| die "$mod: Unable to load module"
 		fi
@@ -437,4 +498,10 @@ lock_chip() {
 	io386 -o b -b x $APM_CNT $VAULT_LOCK
 	echo "Common locking"
 	io386 -o b -b x $APM_CNT $COMMON_LOCK
+}
+
+measure_ldr() {
+	mkdir -p /mnt/ldr
+	mount -o ro "$CONFIG_LDR_DEV" /mnt/ldr
+	tpmr extend -ix 5 -ic `find /mnt/ldr -type f -exec sha256sum {} \; | sha256sum`
 }
