Changelog-public-20250422:
* Add an option to measure kernel, modules, and cmdline into tpm
* Make verification of boot config signature optional, with an
  exemplar target
* Use openssl(1) to deal with password in tpm2_sealfile() and
  tpm2_unseal()
* Add an option to control whether to verify initrd during boot
* Bump busybox to 1.33.2
* Use cryptsetup-2.6.1 for cryptsetup2
* Upgrade openssl, tpm2-tss and tpm2-tools
* Bump gpg to 2.4.2
* Bump Linux kernel to 6.1.8
* Bump util-linux to 2.39
* Bump flashrom to 1.5.1 by resuming its Makefile build system
  to include some key fixes for Intel chipsets

diff --git a/initrd/bin/kexec-boot b/initrd/bin/kexec-boot
--- a/initrd/bin/kexec-boot
+++ b/initrd/bin/kexec-boot
@@ -77,6 +77,11 @@ do
 		else
 			kexeccmd="$kexeccmd -l $filepath"
 		fi
+		if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] \
+			   && [ "$CONFIG_MEASURE_KERNEL" = "y" -a "$dryrun" != "y" ]; then
+			# Measure the kernel into PCR 7, permit failure.
+			tpmr extend -ix 7 -if "$filepath" || true
+		fi
 	fi
 	if [ "$key" = "module" ]; then
 		fix_file_path
@@ -96,6 +101,13 @@ do
 		fi
 		module_number=`expr $module_number + 1`
 		kexeccmd="$kexeccmd --module \"$filepath $cmdline\""
+		if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] \
+			   && [ "$CONFIG_MEASURE_KERNEL" = "y" -a "$dryrun" != "y" ]; then
+			# Measure the module into PCR 9, permit failure.
+			tpmr extend -ix 9 -if "$filepath" || true
+			# Measure the cmd line into PCR 8, permit failure.
+			tpmr extend -ix 8 -ic "$cmdline" || true
+		fi
 	fi
 	if [ "$key" = "initrd" ]; then
 		fix_file_path
@@ -107,11 +119,21 @@ do
 			filepath="$override_initrd"
 		fi
 		kexeccmd="$kexeccmd --initrd=$filepath"
+		if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] \
+			   && [ "$CONFIG_MEASURE_KERNEL" = "y" -a "$dryrun" != "y" ]; then
+			# Measure the initrd into PCR 9, permit failure.
+			tpmr extend -ix 9 -if "$filepath" || true
+		fi
 	fi
 	if [ "$key" = "append" ]; then
 		cmdline="$firstval $restval"
 		adjust_cmd_line
 		kexeccmd="$kexeccmd --append=\"$cmdline\""
+		if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] \
+			   && [ "$CONFIG_MEASURE_KERNEL" = "y" -a "$dryrun" != "y" ]; then
+			# Measure the cmd line into PCR 8, permit failure.
+			tpmr extend -ix 8 -ic "$cmdline" || true
+		fi
 	fi
 done << EOF
 $kexecparams
@@ -120,6 +142,11 @@ EOF
 if [ "$adjusted_cmd_line" = "n" ]; then
 	if [ "$kexectype" = "elf" ]; then
 		kexeccmd="$kexeccmd --append=\"$cmdadd\""
+		if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ] \
+			   && [ "$CONFIG_MEASURE_KERNEL" = "y" -a "$dryrun" != "y" ]; then
+			# Measure the cmd line into PCR 8, permit failure.
+			tpmr extend -ix 8 -ic "$cmdadd" || true
+		fi
 	else
 		die "Failed to add required kernel commands: $cmdadd"
 	fi
@@ -133,11 +160,19 @@ eval "$kexeccmd" \
 || die "Failed to load the new kernel"
 
 if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+	# Flush sessions and transient objects
+	tpm2 flushcontext -Q --transient-object \
+		|| warn "tpm2_flushcontext: unable to flush transient handles"
+	tpm2 flushcontext -Q --loaded-session \
+		|| warn "tpm2_flushcontext: unable to flush sessions"
+	tpm2 flushcontext -Q --saved-session \
+		|| warn "tpm2_flushcontext: unable to flush saved session"
+
 	# Add a random passphrase to platform hierarchy to prevent TPM2 from
 	# being cleared in the OS.
 	# This passphrase is only effective before the next boot.
 	echo "Locking platform hierarchy..."
-	randpass=$(dd if=/dev/urandom bs=4 count=1 | xxd -p)
+	randpass=$(dd if=/dev/urandom bs=4 count=1 | xxd -pc4)
 	tpm2 changeauth -c platform "$randpass" \
 		|| warn "Failed to lock platform hierarchy of TPM2!"
 fi
diff --git a/initrd/bin/kexec-save-default b/initrd/bin/kexec-save-default
--- a/initrd/bin/kexec-save-default
+++ b/initrd/bin/kexec-save-default
@@ -38,11 +38,6 @@ if [ ! -r "$TMP_MENU_FILE" ]; then
 	die "No menu options available, please run kexec-select-boot"
 fi
 
-entry=`head -n $index $TMP_MENU_FILE | tail -1`
-if [ -z "$entry" ]; then
-	die "Invalid menu index $index"
-fi
-
 KEY_DEVICES="$paramsdir/kexec_key_devices.txt"
 KEY_LVM="$paramsdir/kexec_key_lvm.txt"
 save_key="n"
@@ -123,18 +118,33 @@ if [ ! -d $paramsdir ]; then
 fi
 
 if [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
-	if [ ! -r "$PRIMHASH_FILE" ]; then
+	if [ ! -r "$PRIMHASH_FILE" || sha256sum -c "$PRIMHASH_FILE" ]; then
+		echo "(re)Generating TPM2 primary key hash..."
 		sha256sum /tmp/primary.handle > "$PRIMHASH_FILE" \
 			|| die "ERROR: Failed to Hash TPM2 primary key handle!"
 	fi
 fi
 
 rm $paramsdir/kexec_default.*.txt 2>/dev/null || true
-echo "$entry" > $ENTRY_FILE
-cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f | \
-	xargs sha256sum > $HASH_FILE \
-|| die "Failed to create hashes of boot files"
-if [ ! -r $ENTRY_FILE -o ! -r $HASH_FILE ]; then
+if [ "$CONFIG_SIGN_BOOT_CONFIG" = "y" ]; then
+	entry=`head -n $index $TMP_MENU_FILE | tail -1`
+	if [ -z "$entry" ]; then
+		die "Invalid menu index $index"
+	fi
+	echo "$entry" > $ENTRY_FILE
+	option="-F"
+	match=""
+	initrd=`kexec-boot -b "$bootdir" -e "$entry" -i`
+	if [ "$CONFIG_VERIFY_INITRD" != "y" -o -r "${initrd}.sig" ]; then
+		option="-Fv"
+		match="`basename ${initrd}`"
+	fi
+	( cd $bootdir && kexec-boot -b "$bootdir" -e "$entry" -f \
+			| grep "$option" "$match" \
+			| xargs sha256sum > $HASH_FILE \
+	) || die "Failed to create hashes of boot files"
+fi
+if [ "$CONFIG_SIGN_BOOT_CONFIG" = "y" ] && [ ! -r $HASH_FILE -o ! -r $ENTRY_FILE ]; then
 	die "Failed to write default config"
 fi
 
@@ -145,8 +155,10 @@ if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ];then
 		extparam=-r
 	fi
 fi
-kexec-sign-config -p $paramsdir $extparam \
-|| die "Failed to sign default config"
+if [ -x /bin/gpg ]; then
+	kexec-sign-config -p $paramsdir $extparam \
+		|| die "Failed to sign default config"
+fi
 
 # switch back to ro mode
 mount -o ro,remount $paramsdev
diff --git a/initrd/bin/kexec-save-key b/initrd/bin/kexec-save-key
--- a/initrd/bin/kexec-save-key
+++ b/initrd/bin/kexec-save-key
@@ -65,9 +65,11 @@ if [ "$skip_sign" != "y" ]; then
 	if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
 		extparam=-r
 	fi
-	# sign and auto-roll config counter
-	kexec-sign-config -p $paramsdir $extparam \
-	|| die "Failed to sign updated config"
+	if [ -x /bin/gpg ]; then
+		# sign and auto-roll config counter
+		kexec-sign-config -p $paramsdir $extparam \
+			|| die "Failed to sign updated config"
+	fi
 fi
 
 # switch back to ro mode
diff --git a/initrd/bin/mount-usb b/initrd/bin/mount-usb
--- a/initrd/bin/mount-usb
+++ b/initrd/bin/mount-usb
@@ -8,8 +8,18 @@ if ! lsmod | grep -q usb_storage; then
   count=$(ls /dev/sd* 2>/dev/null | wc -l)
   timeout=0
   echo "Scanning for USB storage devices..."
-  insmod /lib/modules/usb-storage.ko >/dev/null 2>&1 \
+  insmod /lib/modules/usb-storage.ko \
   || die "usb_storage: module load failed"
+  if [ -r "/lib/modules/mmc_core.ko" ]; then
+    enable_mmc_core
+    for mod in rtsx_usb rtsx_usb_sdmmc vub300; do
+      if [ -r "/lib/modules/$mod.ko" ] \
+	  && ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
+        insmod "/lib/modules/$mod.ko" \
+        || die "$mod: Unable to load module"
+      fi
+    done
+  fi
   while [[ $count == $(ls /dev/sd* 2>/dev/null | wc -l) ]]; do 
     [[ $timeout -ge 4 ]] && break
     sleep 1
diff --git a/initrd/bin/tpmr b/initrd/bin/tpmr
--- a/initrd/bin/tpmr
+++ b/initrd/bin/tpmr
@@ -126,24 +126,31 @@ tpm2_sealfile() {
 	mkdir -p "$SECRET_DIR"
 	bname="`basename $file`"
 	tpm2 createpolicy --policy-pcr -l "$pcrl" -f "$pcrf" -L "$SECRET_DIR/pcr.policy"
-	if [ "$pass" ];then
-		tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE" -p "$pass"
+	# As stated in https://github.com/tpm2-software/tpm2-tools/issues/642 , sealing with
+	# BOTH policy and password required to unseal is not possible, so if password is needed,
+	# openssl is used to encrypt the file first.
+	if [ "$pass" ]; then
+		[ -x /bin/openssl ] || die "openssl(1) is required to deal with password"
+		openssl enc -aes-256-ctr -nosalt -pbkdf2 -k "$pass" -in "$file" \
+		    | tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i- -r "$SECRET_DIR/$bname.priv" -u "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE"
 	else
-		tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i "$file" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE"
+		tpm2 create -C "/tmp/$PRIMARY_HANDLE_FILE" -i "$file" -r "$SECRET_DIR/$bname.priv" -u "$SECRET_DIR/$bname.pub" -L "$SECRET_DIR/pcr.policy" -S "/tmp/$DEC_SESSION_FILE"
 	fi
-	tpm2 load -C "/tmp/$PRIMARY_HANDLE_FILE" -u "$SECRET_DIR/$bname.priv" -r "$SECRET_DIR/$bname.pub" -c "$SECRET_DIR/$bname.seal.ctx"
-	read -s -p "New TPM owner password: " key_password
+	tpm2 load -C "/tmp/$PRIMARY_HANDLE_FILE" -r "$SECRET_DIR/$bname.priv" -u "$SECRET_DIR/$bname.pub" -c "$SECRET_DIR/$bname.seal.ctx"
+	read -s -p "TPM owner password: " key_password
 	# remove possible data occupying this handle
 	tpm2 evictcontrol -C o -P "$key_password" -c "$handle" 2>/dev/null || true
-	tpm2 evictcontrol -C o -P "$key_password" -c "$SECRET_DIR/$bname.seal.ctx" "$handle" 
+	tpm2 evictcontrol -C o -P "$key_password" -c "$SECRET_DIR/$bname.seal.ctx" "$handle"
 }
 
 tpm2_unseal() {
 	handle="$1"
 	pcrl="$2"
 	pass="$3"
-	if [ "$pass" ];then
-		tpm2 unseal -c "$handle" -S "/tmp/$ENC_SESSION_FILE" -p "pcr:$pcrl+$pass"
+	if [ "$pass" ]; then
+		[ -x /bin/openssl ] || die "openssl(1) is required to deal with password"
+		tpm2 unseal -c "$handle" -S "/tmp/$ENC_SESSION_FILE" -p "pcr:$pcrl" \
+		     | openssl enc -aes-256-ctr -d -nosalt -pbkdf2 -k "$pass"
 	else
 		tpm2 unseal -c "$handle" -S "/tmp/$ENC_SESSION_FILE" -p "pcr:$pcrl"
 	fi
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -3,11 +3,13 @@
 
 die() {
 	echo >&2 "$*";
+	sleep 2;
 	exit 1;
 }
 
 warn() {
 	echo >&2 "$*";
+	sleep 1;
 }
 
 recovery() {
@@ -36,8 +38,6 @@ recovery() {
 		else
 			/bin/ash
 		fi
-		# clear screen
-		printf "\033c"
 	done
 }
 
@@ -111,6 +111,11 @@ enable_mmc_core()
 
 enable_usb()
 {
+	#insmod ehci_hcd prior of uhci_hcd and ohci_hcd to suppress dmesg warning
+	if ! lsmod | grep -q ehci_hcd; then
+		insmod /lib/modules/ehci-hcd.ko \
+		|| die "ehci_hcd: module load failed"
+	fi
 	if [ "$CONFIG_LINUX_USB_COMPANION_CONTROLLER" = y ]; then
 		if ! lsmod | grep -q uhci_hcd; then
 			insmod /lib/modules/uhci-hcd.ko \
@@ -124,10 +129,6 @@ enable_usb()
 			insmod /lib/modules/ohci-pci.ko \
 			|| die "ohci_pci: module load failed"
 		fi
-	fi
-	if ! lsmod | grep -q ehci_hcd; then
-		insmod /lib/modules/ehci-hcd.ko \
-		|| die "ehci_hcd: module load failed"
 	fi
 	if ! lsmod | grep -q ehci_pci; then
 		insmod /lib/modules/ehci-pci.ko \
@@ -148,16 +149,6 @@ enable_usb()
 			insmod /lib/modules/usbhid.ko \
 			|| die "usbhid: module load failed"
 		fi
-	fi
-
-	if [ -r "/lib/modules/mmc_core.ko" ]; then
-		enable_mmc_core
-		for mod in rtsx_usb rtsx_usb_sdmmc vub300; do
-			if [ -r "/lib/modules/$mod.ko" ] && ! lsmod | grep -q "^$(echo $mod | sed 's/-/_/g') " ; then
-				insmod "/lib/modules/$mod.ko" \
-					|| die "$mod: Unable to load module"
-			fi
-		done
 	fi
 }
 
@@ -315,7 +306,7 @@ check_config() {
 		|| die 'Failed to empty kexec tmp dir'
 	fi
 
-	if [ ! -r $1/kexec.sig ]; then
+	if [ "$2" != "force" -a ! -r $1/kexec.sig ]; then
 		return
 	fi
 
@@ -323,9 +314,22 @@ check_config() {
 		return
 	fi
 
-	if [ "$2" != "force" ]; then
+	if [ ! -x /bin/gpg -o "$2" != "force" ]; then
 		if ! sha256sum `find $1/kexec*.txt` | gpgv $1/kexec.sig - ; then
 			die 'Invalid signature on kexec boot params'
+		fi
+		if [ "$CONFIG_VERIFY_INITRD" = "y" ]; then
+			local entry=`cat $1/kexec_default.*.txt | head -1`
+			local initrd=`kexec-boot -b "$1" -e "$entry" -i`
+			if ! grep -q "`basename ${initrd}`" \
+				"$1/kexec_default_hashes.txt" ; then
+				if [ -r "${initrd}.sig" ] \
+					&& gpgv "${initrd}.sig" "${initrd}" ; then
+					echo "+++ Found verified `basename ${initrd}`"
+				else
+					die "No valid signature on `basename ${initrd}`"
+				fi
+			fi
 		fi
 	fi
 
@@ -370,8 +374,6 @@ combine_configs() {
 
 update_checksums()
 {
-	# clear screen
-	printf "\033c"
 	# ensure /boot mounted
 	if ! grep -q /boot /proc/mounts ; then
 		mount -o ro /boot \
@@ -388,10 +390,12 @@ update_checksums()
 			extparam=-r
 		fi
 	fi
-	if ! kexec-sign-config -p /boot -u $extparam ; then
-		rv=1
-	else
-		rv=0
+	if [ "$CONFIG_SIGN_BOOT_CONFIG" = "y" ]; then
+		if ! kexec-sign-config -p /boot -u $extparam ; then
+			rv=1
+		else
+			rv=0
+		fi
 	fi
 
 	# switch back to ro mode
@@ -464,8 +468,8 @@ detect_boot_device()
 }
 
 calc()
-{ 
-	awk "BEGIN { print "$*" }"; 
+{
+	awk "BEGIN { print "$*" }";
 }
 
 print_battery_health()
